# Site settings
title: Eric Anger
header-img: img/home-bg.jpg
email: eric@ericanger.me
description: "A personal blog about the technology, programming, and the PhD lifestyle."
baseurl: ""
url: "http://eanger.github.io"
twitter_username: eric_anger
github_username:  eanger
facebook_username:  eric.anger

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

theme: jekyll-theme-minimal